version: 2

# List of jobs
jobs:
    # The install job
    install:
        working_directory: ~/project
        docker:
            - image: circleci/node:12.16.1
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v2-dependencies-{{ checksum "package.json" }}
                - v2-dependencies-
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: npm install
            # Cache local dependencies if they don't exist
            - save_cache:
                key: v2-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules

    # The build job
    build:
        working_directory: ~/project
        docker:
            - image: circleci/node:12.16.1
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v2-dependencies-{{ checksum "package.json" }}
                - v2-dependencies-
            # Run compile
            - run:
                name: Truffle compile
                command: npm run compile:sol
            # Save build
            - store_artifacts:
                path: build

    # The test job
    test:
        working_directory: ~/project
        docker:
            - image: circleci/node:12.16.1
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v2-dependencies-{{ checksum "package.json" }}
                - v2-dependencies-
            # Run truffle test
            - run:
                name: Run truffle tests
                command: npm run test

    # The coverage job
    coverage:
        working_directory: ~/project
        docker:
            - image: circleci/node:12.16.1
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v2-dependencies-{{ checksum "package.json" }}
                - v2-dependencies-
            # Run coverage
            - run:
                name: solidity-coverage
                no_output_timeout: 30m
                command:
                  rm -rf node_modules &&
                  npm install &&
                  npm run coverage
            # Upload results
            - run:
                name: Upload coverage to coveralls
                command: cat coverage/lcov.info | node_modules/.bin/coveralls
            # Save artifacts
            - store_artifacts:
                path: coverage

    # The lint-javascript job
    lint-javascript:
        working_directory: ~/project
        docker:
            - image: circleci/node:12.16.1
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v2-dependencies-{{ checksum "package.json" }}
                - v2-dependencies-
            # Run lint javascript
            - run:
                name: ESLint
                command: npm run lint:js

    # The lint-solidity job
    lint-solidity:
        working_directory: ~/project
        docker:
            - image: circleci/node:12.16.1
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v2-dependencies-{{ checksum "package.json" }}
                - v2-dependencies-
            # Run Solidity lint
            - run:
                name: Solhint
                command: npm run lint:sol

workflows:
    version: 2
    # The build and deploy workflow
    build_and_test:
        jobs:
            - install
            - build:
                requires:
                    - install
            - test:
                requires:
                    - install
            - coverage:
                requires:
                    - install
            - lint-javascript:
                requires:
                    - install
            - lint-solidity:
                requires:
                    - install
